// USERS
export const FETCH_USER = "FETCH_USER";
export const LOGOUT = "LOGOUT";
export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const RECEIVE_LOGIN = "RECEIVE_LOGIN";
export const RECEIVE_LOGIN_ERROR = "RECEIVE_LOGIN_ERROR";
export const REQUEST_ADD_USER = "REQUEST_ADD_USER";
export const RECEIVE_ADD_USER = "RECEIVE_ADD_USER";
export const REQUEST_ERROR = "REQUEST_ERROR";

// ADVENTURES
export const DELETE_ADVENTURE = "DELETE_ADVENTURE";
export const CHOOSE_ADVENTURE = "CHOOSE_ADVENTURE";

export const REQUEST_GET_ADVENTURES = "REQUEST_GET_ADVENTURES";
export const RECEIVE_GET_ADVENTURES = "RECEIVE_GET_ADVENTURES";
export const REQUEST_ADD_ADVENTURE = "REQUEST_ADD_ADVENTURE";
export const RECEIVE_ADD_ADVENTURE = "RECEIVE_ADD_ADVENTURE";
export const REQUEST_EDIT_ADVENTURE = "REQUEST_EDIT_ADVENTURE";
export const RECEIVE_EDIT_ADVENTURE = "RECEIVE_EDIT_ADVENTURE";
export const REQUEST_GET_PLAYERS = "REQUEST_GET_PLAYERS";
export const RECEIVE_GET_PLAYERS = "RECEIVE_GET_PLAYERS";

// ADVENTURES :: Currently Unused
export const REQUEST_DELETE_ADVENTURE = "REQUEST_DELETE_ADVENTURE";
export const RECEIVE_DELETE_ADVENTURE = "RECEIVE_DELETE_ADVENTURE";

export const SET_SESSION = "SET_SESSION";
export const SAVE_ADVENTURE = "SAVE_ADVENTURE";
export const NEW_ADVENTURE = "NEW_ADVENTURE";
export const BEGIN_SESSION = "BEGIN_SESSION";


// COMBAT
export const NEW_EVENT = "NEW_EVENT";
export const BEGIN_COMBAT = "BEGIN_COMBAT";
export const FINISH_COMBAT = "FINISH_COMBAT";

// SESSION
export const CLEAR_NEWS = "CLEAR_NEWS";
export const TOGGLE_HERO = "TOGGLE_HERO";
export const CONFIGURE_COMBAT = "CONFIGURE_COMBAT";
export const ADD_ENEMY = "ADD_ENEMY";
export const PICK_ENEMY = "PICK_ENEMY";
export const REMOVE_ENEMY = "REMOVE_ENEMY";
export const CANCEL = "CANCEL";


// SETTINGS
export const SET_SETTINGS = "SET_SETTINGS"
export const SELECT_SETTING = "SELECT_SETTING";
export const UPDATE_SETTING = "UPDATE_SETTING";

export const REQUEST_GET_SETTINGS = "REQUEST_GET_SETTINGS";
export const RECEIVE_GET_SETTINGS = "RECEIVE_GET_SETTINGS";
